//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/piiilk_ARPGDemo/Scripts/Input/GameInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputAction"",
    ""maps"": [
        {
            ""name"": ""GameInputBase"",
            ""id"": ""ce5622fe-0dd0-4138-9120-e9b35d8bdede"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""a7900bf1-31dd-4e1a-b9fc-19e7ef8ade2f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""6f054bfa-bb25-47bc-b3a8-590fd6cf9efe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""4fb8214e-7b1a-4c79-bf57-43d1e86aa7df"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""3eadc30a-674b-483c-8d00-991abc9a9303"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lock"",
                    ""type"": ""Button"",
                    ""id"": ""25b8c61b-52b6-4d96-a19f-4c19078d75a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakeOutSword"",
                    ""type"": ""Button"",
                    ""id"": ""d533665c-a154-4cde-b943-345b3dcfd0c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LAttack"",
                    ""type"": ""Button"",
                    ""id"": ""60a47ad6-c30e-494e-88c2-476c836316d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RAttack"",
                    ""type"": ""Button"",
                    ""id"": ""78865d83-ac46-4799-a833-1ac194d3958b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Finish"",
                    ""type"": ""Button"",
                    ""id"": ""47434a2b-37e0-42ee-a857-c6791b235eeb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""13e2a01f-a796-4b9c-a318-53449bf97eb8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrailTest"",
                    ""type"": ""Button"",
                    ""id"": ""9663d1b3-cc98-4de3-ab32-36761395cada"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""bda242da-ce76-4247-9255-5c225f341aad"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2a862fd7-7eb0-44bd-b9ca-b91ec8fbdc4a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""53e6e153-e9b2-4fd0-90be-e06841172d81"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9dd80104-26ff-42b8-a49a-4fe50f4062dc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""976af6d1-ba4a-4e1f-aa89-de1ce361e62f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""82693bf9-9ba8-4fdd-9a05-3205854d3738"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd106312-72de-4d48-8af9-82e89fed86ad"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c027481b-0a51-4308-83d5-affc6b47f555"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72519cf0-89b3-4ee7-8ec5-3050de29a7ae"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""548a8b18-c874-476c-bdb4-cde7b7eb4141"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeOutSword"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""891551fd-d228-4cd0-896c-1fac946f4161"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8243051a-a669-4296-b779-8ef7b0834801"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ee13822-5648-48d6-9ad1-4eea657969aa"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Finish"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96b779af-10d1-4e5d-8274-ef872486baff"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14107604-9dd0-44e1-a8c4-b4b0e20a215f"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrailTest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameInputBase
        m_GameInputBase = asset.FindActionMap("GameInputBase", throwIfNotFound: true);
        m_GameInputBase_Movement = m_GameInputBase.FindAction("Movement", throwIfNotFound: true);
        m_GameInputBase_Run = m_GameInputBase.FindAction("Run", throwIfNotFound: true);
        m_GameInputBase_MouseDelta = m_GameInputBase.FindAction("MouseDelta", throwIfNotFound: true);
        m_GameInputBase_Dash = m_GameInputBase.FindAction("Dash", throwIfNotFound: true);
        m_GameInputBase_Lock = m_GameInputBase.FindAction("Lock", throwIfNotFound: true);
        m_GameInputBase_TakeOutSword = m_GameInputBase.FindAction("TakeOutSword", throwIfNotFound: true);
        m_GameInputBase_LAttack = m_GameInputBase.FindAction("LAttack", throwIfNotFound: true);
        m_GameInputBase_RAttack = m_GameInputBase.FindAction("RAttack", throwIfNotFound: true);
        m_GameInputBase_Finish = m_GameInputBase.FindAction("Finish", throwIfNotFound: true);
        m_GameInputBase_Block = m_GameInputBase.FindAction("Block", throwIfNotFound: true);
        m_GameInputBase_TrailTest = m_GameInputBase.FindAction("TrailTest", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameInputBase
    private readonly InputActionMap m_GameInputBase;
    private List<IGameInputBaseActions> m_GameInputBaseActionsCallbackInterfaces = new List<IGameInputBaseActions>();
    private readonly InputAction m_GameInputBase_Movement;
    private readonly InputAction m_GameInputBase_Run;
    private readonly InputAction m_GameInputBase_MouseDelta;
    private readonly InputAction m_GameInputBase_Dash;
    private readonly InputAction m_GameInputBase_Lock;
    private readonly InputAction m_GameInputBase_TakeOutSword;
    private readonly InputAction m_GameInputBase_LAttack;
    private readonly InputAction m_GameInputBase_RAttack;
    private readonly InputAction m_GameInputBase_Finish;
    private readonly InputAction m_GameInputBase_Block;
    private readonly InputAction m_GameInputBase_TrailTest;
    public struct GameInputBaseActions
    {
        private @GameInputAction m_Wrapper;
        public GameInputBaseActions(@GameInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_GameInputBase_Movement;
        public InputAction @Run => m_Wrapper.m_GameInputBase_Run;
        public InputAction @MouseDelta => m_Wrapper.m_GameInputBase_MouseDelta;
        public InputAction @Dash => m_Wrapper.m_GameInputBase_Dash;
        public InputAction @Lock => m_Wrapper.m_GameInputBase_Lock;
        public InputAction @TakeOutSword => m_Wrapper.m_GameInputBase_TakeOutSword;
        public InputAction @LAttack => m_Wrapper.m_GameInputBase_LAttack;
        public InputAction @RAttack => m_Wrapper.m_GameInputBase_RAttack;
        public InputAction @Finish => m_Wrapper.m_GameInputBase_Finish;
        public InputAction @Block => m_Wrapper.m_GameInputBase_Block;
        public InputAction @TrailTest => m_Wrapper.m_GameInputBase_TrailTest;
        public InputActionMap Get() { return m_Wrapper.m_GameInputBase; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameInputBaseActions set) { return set.Get(); }
        public void AddCallbacks(IGameInputBaseActions instance)
        {
            if (instance == null || m_Wrapper.m_GameInputBaseActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameInputBaseActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @MouseDelta.started += instance.OnMouseDelta;
            @MouseDelta.performed += instance.OnMouseDelta;
            @MouseDelta.canceled += instance.OnMouseDelta;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @Lock.started += instance.OnLock;
            @Lock.performed += instance.OnLock;
            @Lock.canceled += instance.OnLock;
            @TakeOutSword.started += instance.OnTakeOutSword;
            @TakeOutSword.performed += instance.OnTakeOutSword;
            @TakeOutSword.canceled += instance.OnTakeOutSword;
            @LAttack.started += instance.OnLAttack;
            @LAttack.performed += instance.OnLAttack;
            @LAttack.canceled += instance.OnLAttack;
            @RAttack.started += instance.OnRAttack;
            @RAttack.performed += instance.OnRAttack;
            @RAttack.canceled += instance.OnRAttack;
            @Finish.started += instance.OnFinish;
            @Finish.performed += instance.OnFinish;
            @Finish.canceled += instance.OnFinish;
            @Block.started += instance.OnBlock;
            @Block.performed += instance.OnBlock;
            @Block.canceled += instance.OnBlock;
            @TrailTest.started += instance.OnTrailTest;
            @TrailTest.performed += instance.OnTrailTest;
            @TrailTest.canceled += instance.OnTrailTest;
        }

        private void UnregisterCallbacks(IGameInputBaseActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @MouseDelta.started -= instance.OnMouseDelta;
            @MouseDelta.performed -= instance.OnMouseDelta;
            @MouseDelta.canceled -= instance.OnMouseDelta;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @Lock.started -= instance.OnLock;
            @Lock.performed -= instance.OnLock;
            @Lock.canceled -= instance.OnLock;
            @TakeOutSword.started -= instance.OnTakeOutSword;
            @TakeOutSword.performed -= instance.OnTakeOutSword;
            @TakeOutSword.canceled -= instance.OnTakeOutSword;
            @LAttack.started -= instance.OnLAttack;
            @LAttack.performed -= instance.OnLAttack;
            @LAttack.canceled -= instance.OnLAttack;
            @RAttack.started -= instance.OnRAttack;
            @RAttack.performed -= instance.OnRAttack;
            @RAttack.canceled -= instance.OnRAttack;
            @Finish.started -= instance.OnFinish;
            @Finish.performed -= instance.OnFinish;
            @Finish.canceled -= instance.OnFinish;
            @Block.started -= instance.OnBlock;
            @Block.performed -= instance.OnBlock;
            @Block.canceled -= instance.OnBlock;
            @TrailTest.started -= instance.OnTrailTest;
            @TrailTest.performed -= instance.OnTrailTest;
            @TrailTest.canceled -= instance.OnTrailTest;
        }

        public void RemoveCallbacks(IGameInputBaseActions instance)
        {
            if (m_Wrapper.m_GameInputBaseActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameInputBaseActions instance)
        {
            foreach (var item in m_Wrapper.m_GameInputBaseActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameInputBaseActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameInputBaseActions @GameInputBase => new GameInputBaseActions(this);
    public interface IGameInputBaseActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnLock(InputAction.CallbackContext context);
        void OnTakeOutSword(InputAction.CallbackContext context);
        void OnLAttack(InputAction.CallbackContext context);
        void OnRAttack(InputAction.CallbackContext context);
        void OnFinish(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
        void OnTrailTest(InputAction.CallbackContext context);
    }
}
